version: "3.8"

services:
  opensearch:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env/ENV-local.env
    ports:
      - "9200:9200"    # REST API
      - "9600:9600"    # Performance Analyzer
      - "5005:5005"    # Debug port
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  opensearch-data: