version: "3.8"

services:
  opensearch:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "9200:9200"    # REST API
      - "9600:9600"    # Performance Analyzer
      - "5005:5005"    # Debug port
    volumes:
      - opensearch-data:/usr/share/opensearch/data

volumes:
  opensearch-data: